language: python
python:
  - "2.7"
install: 
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - pip install coveralls
script:  
  - nosetests --with-coverage --cover-package=cuatro
after_success:
  - coveralls
